/*=====================Latte=====================*/
#define CATPPUCCIN_LATTE_ROSEWATER          0xdc4f
#define CATPPUCCIN_LATTE_FLAMINGO           0xdbcf
#define CATPPUCCIN_LATTE_PINK               0xebb9
#define CATPPUCCIN_LATTE_MAUVE              0x89dd
#define CATPPUCCIN_LATTE_RED                0xd067
#define CATPPUCCIN_LATTE_MAROON             0xe22a
#define CATPPUCCIN_LATTE_PEACH              0xfb21
#define CATPPUCCIN_LATTE_YELLOW             0xdc63
#define CATPPUCCIN_LATTE_GREEN              0x4505
#define CATPPUCCIN_LATTE_TEAL               0x1493
#define CATPPUCCIN_LATTE_SKY                0x53c
#define CATPPUCCIN_LATTE_SAPPHIRE           0x24f6
#define CATPPUCCIN_LATTE_BLUE               0x1b3e
#define CATPPUCCIN_LATTE_LAVENDER           0x743f
#define CATPPUCCIN_LATTE_TEXT               0x4a6d
#define CATPPUCCIN_LATTE_SUBTEXT1           0x5aee
#define CATPPUCCIN_LATTE_SUBTEXT0           0x6b70
#define CATPPUCCIN_LATTE_OVERLAY2           0x7bf2
#define CATPPUCCIN_LATTE_OVERLAY1           0x8c74
#define CATPPUCCIN_LATTE_OVERLAY0           0x9d16
#define CATPPUCCIN_LATTE_SURFACE2           0xad97
#define CATPPUCCIN_LATTE_SURFACE1           0xbe19
#define CATPPUCCIN_LATTE_SURFACE0           0xce9b
#define CATPPUCCIN_LATTE_BASE               0xef9e
#define CATPPUCCIN_LATTE_MANTLE             0xe75d
#define CATPPUCCIN_LATTE_CRUST              0xdf1d

/*====================Frappé=====================*/
#define CATPPUCCIN_FRAPPE_ROSEWATER         0xf6b9
#define CATPPUCCIN_FRAPPE_FLAMINGO          0xedf7
#define CATPPUCCIN_FRAPPE_PINK              0xf5dc
#define CATPPUCCIN_FRAPPE_MAUVE             0xccfc
#define CATPPUCCIN_FRAPPE_RED               0xe410
#define CATPPUCCIN_FRAPPE_MAROON            0xecd3
#define CATPPUCCIN_FRAPPE_PEACH             0xecee
#define CATPPUCCIN_FRAPPE_YELLOW            0xe652
#define CATPPUCCIN_FRAPPE_GREEN             0xa691
#define CATPPUCCIN_FRAPPE_TEAL              0x8657
#define CATPPUCCIN_FRAPPE_SKY               0x9e9b
#define CATPPUCCIN_FRAPPE_SAPPHIRE          0x861b
#define CATPPUCCIN_FRAPPE_BLUE              0x8d5d
#define CATPPUCCIN_FRAPPE_LAVENDER          0xbdde
#define CATPPUCCIN_FRAPPE_TEXT              0xc69e
#define CATPPUCCIN_FRAPPE_SUBTEXT1          0xb5fc
#define CATPPUCCIN_FRAPPE_SUBTEXT0          0xa579
#define CATPPUCCIN_FRAPPE_OVERLAY2          0x94f7
#define CATPPUCCIN_FRAPPE_OVERLAY1          0x8454
#define CATPPUCCIN_FRAPPE_OVERLAY0          0x73d2
#define CATPPUCCIN_FRAPPE_SURFACE2          0x6350
#define CATPPUCCIN_FRAPPE_SURFACE1          0x52ad
#define CATPPUCCIN_FRAPPE_SURFACE0          0x422b
#define CATPPUCCIN_FRAPPE_BASE              0x31a8
#define CATPPUCCIN_FRAPPE_MANTLE            0x2967
#define CATPPUCCIN_FRAPPE_CRUST             0x2126

/*===================Macchiato===================*/
#define CATPPUCCIN_MACCHIATO_ROSEWATER      0xf6da
#define CATPPUCCIN_MACCHIATO_FLAMINGO       0xf638
#define CATPPUCCIN_MACCHIATO_PINK           0xf5fc
#define CATPPUCCIN_MACCHIATO_MAUVE          0xc51e
#define CATPPUCCIN_MACCHIATO_RED            0xec32
#define CATPPUCCIN_MACCHIATO_MAROON         0xecd4
#define CATPPUCCIN_MACCHIATO_PEACH          0xf54f
#define CATPPUCCIN_MACCHIATO_YELLOW         0xeeb3
#define CATPPUCCIN_MACCHIATO_GREEN          0xa6d2
#define CATPPUCCIN_MACCHIATO_TEAL           0x8eb9
#define CATPPUCCIN_MACCHIATO_SKY            0x96bc
#define CATPPUCCIN_MACCHIATO_SAPPHIRE       0x7e3c
#define CATPPUCCIN_MACCHIATO_BLUE           0x8d7e
#define CATPPUCCIN_MACCHIATO_LAVENDER       0xb5ff
#define CATPPUCCIN_MACCHIATO_TEXT           0xce9e
#define CATPPUCCIN_MACCHIATO_SUBTEXT1       0xbe1c
#define CATPPUCCIN_MACCHIATO_SUBTEXT0       0xa579
#define CATPPUCCIN_MACCHIATO_OVERLAY2       0x94d6
#define CATPPUCCIN_MACCHIATO_OVERLAY1       0x8434
#define CATPPUCCIN_MACCHIATO_OVERLAY0       0x6b91
#define CATPPUCCIN_MACCHIATO_SURFACE2       0x5b0f
#define CATPPUCCIN_MACCHIATO_SURFACE1       0x4a6c
#define CATPPUCCIN_MACCHIATO_SURFACE0       0x31c9
#define CATPPUCCIN_MACCHIATO_BASE           0x2127
#define CATPPUCCIN_MACCHIATO_MANTLE         0x1906
#define CATPPUCCIN_MACCHIATO_CRUST          0x18c4

/*=====================Mocha=====================*/
#define CATPPUCCIN_MOCHA_ROSEWATER          0xf71b
#define CATPPUCCIN_MOCHA_FLAMINGO           0xf679
#define CATPPUCCIN_MOCHA_PINK               0xf61c
#define CATPPUCCIN_MOCHA_MAUVE              0xcd3e
#define CATPPUCCIN_MOCHA_RED                0xf455
#define CATPPUCCIN_MOCHA_MAROON             0xed15
#define CATPPUCCIN_MOCHA_PEACH              0xfd90
#define CATPPUCCIN_MOCHA_YELLOW             0xff15
#define CATPPUCCIN_MOCHA_GREEN              0xa714
#define CATPPUCCIN_MOCHA_TEAL               0x971a
#define CATPPUCCIN_MOCHA_SKY                0x8efd
#define CATPPUCCIN_MOCHA_SAPPHIRE           0x763d
#define CATPPUCCIN_MOCHA_BLUE               0x8dbf
#define CATPPUCCIN_MOCHA_LAVENDER           0xb5ff
#define CATPPUCCIN_MOCHA_TEXT               0xcebe
#define CATPPUCCIN_MOCHA_SUBTEXT1           0xbe1b
#define CATPPUCCIN_MOCHA_SUBTEXT0           0xa579
#define CATPPUCCIN_MOCHA_OVERLAY2           0x94d6
#define CATPPUCCIN_MOCHA_OVERLAY1           0x7c33
#define CATPPUCCIN_MOCHA_OVERLAY0           0x6b90
#define CATPPUCCIN_MOCHA_SURFACE2           0x5ace
#define CATPPUCCIN_MOCHA_SURFACE1           0x422b
#define CATPPUCCIN_MOCHA_SURFACE0           0x3188
#define CATPPUCCIN_MOCHA_BASE               0x18e5
#define CATPPUCCIN_MOCHA_MANTLE             0x18c4
#define CATPPUCCIN_MOCHA_CRUST              0x1083

